#!/bin/bash

clear

fun_bar () {

comando[0]="$1"

comando[1]="$2"

 (

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} > /dev/null 2>&1

${comando[1]} > /dev/null 2>&1

touch $HOME/fim

 ) > /dev/null 2>&1 &

 tput civis

echo -ne "   \033[1;33mWait \033[1;37m- \033[1;33m["

while true; do

   for((i=0; i<18; i++)); do

   echo -ne "\033[1;31m#"

   sleep 0.1s

   done

   [[ -e $HOME/fim ]] && rm $HOME/fim && break

   echo -e "\033[1;33m]"

   sleep 1s

   tput cuu1

   tput dl1

   echo -ne "   \033[1;33mWait \033[1;37m- \033[1;33m["

done

echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"

tput cnorm

}

echo " "

fun_atts () {
    [[ -e /tmp/att ]] && rm /tmp/att
    wget -q -O /tmp/att https://raw.githubusercontent.com/tblesshack/SSHPlus/master/Install/versao
    if [[ -f "/tmp/att" ]]; then
        latest_version=$(grep -m1 "VERSAO:" /tmp/att | awk '{print $2}')
    else
        echo "Failed to fetch latest version" > /tmp/att
    fi
} > /dev/null 2>&1

echo -e "                              \033[1;31mBy @tblesshack\033[1;36m"
echo -e "   SSHPlus" | figlet
echo " "

echo -e "   \033[1;32mCHECKING FOR AVAILABLE UPDATES\033[0m\n"
fun_bar 'fun_atts'

if [[ -f "/tmp/att" ]]; then
    latest_version=$(grep -m1 "VERSAO:" /tmp/att | awk '{print $2}')
    current_version=$(grep -m1 "VERSAO:" /bin/versao 2>/dev/null | awk '{print $2}' || echo "0")

    if [[ "$current_version" == "$latest_version" ]]; then
        echo -e " \033[1;36m     THE SCRIPT IS ALREADY UP TO DATE!\033[1;32m\n"
        echo -e " \033[1;33m Current version: \033[1;37m$current_version\n"
        rm /tmp/att > /dev/null 2>&1
        echo -e " \033[1;33m MORE INFORMATION \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@tblesshack\n"
        echo -ne " \033[1;31m ENTER \033[1;33mto return to \033[1;32mMENU!\033[0m"; read
        menu
    else
        echo -e "  \033[1;36mTHERE IS A NEW UPDATE AVAILABLE!\033[1;33m\n"
        echo -e "  \033[1;33mMORE INFORMATION \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@tblesshack\n"
        echo -e "  \033[1;32mUPDATE DETAILS:\033[0m\n"
        echo -e "  \033[1;37m- \033[1;33mCurrent version: $current_version"
        echo -e "  \033[1;37m- \033[1;33mLatest version: $latest_version"
        echo -e "\n  \033[1;37mCHANGELOG:"
        sed -n '/VERSAO:/,$p' /tmp/att | grep -v "VERSAO:" | while read line; do
            echo -e "  \033[1;37m- \033[1;33m$line"
        done
        echo " "
        echo -ne "  \033[1;32mWANT TO UPDATE \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read res
        if [[ "$res" = s || "$res" = S ]];then
            echo -e "\n\033[1;32m  STARTING UPDATE..."
            sleep 3
            wget https://raw.githubusercontent.com/tblesshack/SSHPlus/master/Plus > /dev/null 2>&1
            chmod +x Plus
            ./Plus
            clear
            echo -e "\033[1;32mSCRIPT UPDATED SUCCESSFULLY\033[0m\n"
            rm /tmp/att > /dev/null 2>&1
            echo -ne "\033[1;31mENTER \033[1;33mto return to \033[1;32mMENU!\033[0m"; read
            menu
        else
            menu
        fi
    fi
else
    echo -e "\n\033[1;31m ERROR CONNECTING TO SERVER\n"
    echo -ne "\033[1;31m ENTER \033[1;33mto return to \033[1;32mMENU!\033[0m"; read
    menu
fi